# Generated by Django 4.1.7 on 2023-12-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_blogs_id_alter_contact_id_alter_internship_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='my_file',
            field=models.FileField(default=True, upload_to=''),
        ),
    ]
